### Numpy Crash Course
 03/07/25

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.1'

In [4]:
import sys
sys.version

'3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]'

In [5]:
# Create a List
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:

type(arr)  # ndarray means 'n' dimension array.

numpy.ndarray

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [13]:
np.arange(10,20,40,4) # arange([start,] stop[, step,], dtype=None, *, device=None, like=None) , only 3 args are allowed.

TypeError: Cannot interpret '4' as a data type

In [ ]:
np.arange(20,9)  # the first argument must be less than second argument like this == np.arange(9,20).

In [ ]:
np.arange(9,20)

In [14]:
n = np.arange(-20,9)
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8])

In [15]:
np.zeros(3) # The system bydefault take dtype = float.

array([0., 0., 0.])

In [16]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [17]:
np.zeros(3, int)

array([0, 0, 0])

In [18]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
nd = np.zeros((5,9),int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [21]:
np.ones(3)

array([1., 1., 1.])

In [22]:
np.ones(3,dtype = int)

array([1, 1, 1])

In [23]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [24]:
nd1 = np.ones((10,10),dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [25]:

# 04/07/25

In [26]:
rand

NameError: name 'rand' is not defined

In [27]:
randam.rand(3,4)

NameError: name 'randam' is not defined

In [ ]:
np.random.rand(2)

In [28]:
np.random.rand(3,2)

array([[0.93321057, 0.29431726],
       [0.72685936, 0.92579888],
       [0.80771931, 0.90665942]])

In [29]:
np.random.randint(3    # randint-- random

_IncompleteInputError: incomplete input (2494376950.py, line 1)

In [ ]:
np.random.randint(2,10)

In [ ]:
np.random.randint(2, 10, 4)

In [ ]:
np.random.randint(-38, 20, 10)

In [ ]:
np.random.randint(10,40,(10,10))

In [ ]:
m = np.random.randint(10,40,(10,10))
m

In [ ]:
arr 

In [ ]:
arr.reshape(2,3)  # it uses row * column means here 2= row and 3= column

In [ ]:
arr.reshape(6,1)   # it uses row * column means here 6= row and 1= column

In [ ]:
arr.reshape(1,6)   # it uses row * column means here 1= row and 6= column

In [ ]:
b= np.random.randint(10,20,(5,4))
b

In [ ]:
b[:]

In [30]:
b[1:4]

NameError: name 'b' is not defined

In [ ]:
b[-1 :]

In [31]:
b[:-1]

NameError: name 'b' is not defined

In [ ]:
b[:-1]

In [32]:
b[:-2]

NameError: name 'b' is not defined

In [33]:
b[1,2]

NameError: name 'b' is not defined

In [34]:
b

NameError: name 'b' is not defined

In [ ]:
b[1,-1]

### Numpy Operations

In [35]:
arr

array([0, 1, 2, 3, 4, 5])

In [36]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
row = 4
col = 5

In [38]:
col

5

In [39]:
mat[row,col]

np.int64(45)

In [40]:
mat[1] # to print row

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
mat[:,col] # to print column

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [42]:
mat[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [43]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [44]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [45]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [46]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [47]:
mat[1:2,2:4]

array([[12, 13]])

In [48]:
mat[2:4,4:5]

array([[24],
       [34]])

In [49]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [50]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [51]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Class Test
05/07/25  Class Test and introduction to Streamlit.io (Streamlit is open source frontend framework to build frontend UI simple way.)

### 07/07/25
 Project using Numpy and matplotlib.
### Project- IPL Dataset Analysis.